### ISSUE TITLE
Any tips for new implementation? 

### ISSUE THREAD

**Issue by bezysoftware** [hoytech/negentropy#13]
Hi, I'm planning to write a c# implementation (ultimately to use it for nip77: https://github.com/bezysoftware/netstr/issues/25

Do you have any tips? I briefly went thru your blog post and the js implementation, do you think thats a good place to start, draw inspiration from the js version?

**Comment by hoytech** [comment]
Hi! Yes, I would start from whichever implementation you are most comfortable with. JS is a good one, although there are a few patterns with buffers that probably don't directly translate to other languages.

Once you have it developed, please build a harness program so it can run against the test-suite.

Let us know if you hit any problems. Thanks!

**Comment by bezysoftware** [comment]
Hi @hoytech my implementation is ready, running tests against js implementation passed 🎉 
Available here: https://github.com/bezysoftware/negentropy.net

**Comment by hoytech** [comment]
Thank you! I added a link to your repo in the Implementations section of the README.

**Comment by hoytech** [comment]
...and then I notice that your PR already did it. Merged :+1:
